using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class StarDisplay : MonoBehaviour
{
    [SerializeField] int stars = 100;
    Text starText;

    // Start is called before the first frame update
    void Start()
    {
        starText = GetComponent<Text>();
        UpdateDisplay();
    }

    private void UpdateDisplay()
    {
        starText.text = stars.ToString();
    }

    //This Function allow us Add Star generated by the trophy
    public void AddStars(int amount)
    {
        stars += amount;
        UpdateDisplay(); //each time addstars is called we will update score, better than calling it in update
    }

    //This function allow us to spend star when we plant something
    public void SpendStars(int starCost)
    {
        if (stars>=starCost)
        {
            stars -= starCost;
            UpdateDisplay();
        }
        
    }
}
